apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiassistantservice
  labels:
    app: aiassistantservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiassistantservice
  template:
    metadata:
      labels:
        app: aiassistantservice
    spec:
      containers:
        - name: aiassistantservice
          image: REGION-docker.pkg.dev/PROJECT_ID/images/aiassistantservice:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api
                  key: OPENAI_API_KEY
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "64Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: aiassistantservice
  labels:
    app: aiassistantservice
spec:
  selector:
    app: aiassistantservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
