apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - aiassistantservice.yaml

# (opcional, mas recomendado) patcha o frontend p/ habilitar a UI
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        template:
          spec:
            containers:
            - name: server
              env:
              - name: ENABLE_ASSISTANT
                value: "true"
              - name: SHOPPING_ASSISTANT_SERVICE_ADDR
                value: "aiassistantservice:8080"
